name: SonarCloud
on:
  workflow_dispatch:                             

jobs:
  Code_Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
      - name: Build for Release
      run: dotnet build --configuration Release
     - name: Sonarscanner for dotnet
       uses: Secbyte/dotnet-sonarscanner@v2.3 
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=DermotHayes
            -Dsonar.projectKey=DermotHayes_BPMonitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
